input_dir: data/genomes

mask_threads: 8
predict_threads: 8


samples:
  NCYC357:
    location: "data/genomes/NCYC357_genome.fasta"
    species: "Saccharomyces sp."
    strain: "NCYC357"
    busco_seed_species: "saccharomyces_cerevisiae_S288C" # Para conferir as opções, rode "funannotate species"
